# Unit in [um]
Pad:
  layer: 1
  width: 250
  height: 400
  rounding: 0
  gap: 20 # gap between two capacitance pads

JJ:
  squid: false
  bandage: false
  
  finger:
    layer: 1
    up:
      length: 10.0
      width: 0.2
    down:
      length: 10.0
      width: 0.3
  pad_box:
    width: 2.0
    length: 10
    gap: 4.0
  bridge:
    width: 0.9
  taper:
    width1: 10
    width2: 40
    length: 100
    gap: 10

DicingMarker:
  layer: 1
  width: 100
  # length: 400
  length: 1600

Frame:
  layer: 25
  width: 50
  size:
    height: 10000
    width: 2000

Grid:
  name: "transmon3D"
  layer: 9
  lines:
    x: 12
    y: 10
  sweep:
    ## If you have many parameters to sweep, use gridsweep to make a 2D array
    type: "gridsweep"
    array:
      - param_x: "JJ_finger_down_width"
        param_y: "JJ_bridge_width"
        x: [0.7, 0.8, 0.9, 1.0, 1.1, null, 0.5, 0.6, 0.7, 0.8, 0.9]
        y: [0.15, 0.2, 0.3]
        gap_x: 0
        gap_y: 0
      - param_x : "dummy"
        param_y : "dummy"
        x: [0, 0]
        y: [0, 0]
        gap_x: 1
        gap_y: 1
      # - param_x : "JJ_squid"
      #   param_y : "dummy"
      #   x: [true, false]
      #   y: [0]
      #   gap_x: 1
      #   gap_y: 1

    # # More manual way to place chip designs
    # # Place arguments in the array, where you want samples
    # # Put "null" if you want an empty cell
    # type: "array"
    # devices:
    #   - JJ_finger_width: 0.10
    #     Pad_width : 250
    #     Pad_height : 600
    #   - JJ_finger_width: 0.15
    #     JJ_squid: true
    #     Pad_width : 400
    #   - JJ_finger_width: 0.15
    #     JJ_squid: true
    #     Pad_width : 600
    #     Pad_height : 200
    # array: [
    #   [0    , null  , 1     , null, 1    , null  , 2     , 0   ],
    #   [1    , null  , 2     , 0   , 0    , 1     , 2     , null], 
    #   [0    , 1     , 2     , null, 1    , 0     , null  , 1   ],
    #   [1    , 0     , null  , 1   , 1    , null  , 2     , 0   ], 
    #   [0    , 1     , 2     , null, 1    , 0     , null  , 1   ],
    #   [1    , null  , 2     , 0   , 0    , 1     , 2     , null], 
    # ]
    # gap_x : 0
    # gap_y : 0
  
Text:
  string: '"fw " + str(config["JJ_finger_down_width"]) + "\nbw " + str(config["JJ_bridge_width"])'
  layer: 2
  size: 40
  pos:
    x: -0.8
    y: -0.85